### ISSUE TITLE
Thanks For Your HyperLandmark-iOS Project

### ISSUE THREAD

**Issue by panda-lab** [elhoangvu/HyperLandmark-iOS#1]
Hi,
  We are the author of HyperLandmark, when i search github, i found you have created a ios project. 
Could you give me your email or wechat? I want to make a friend with you! 
Thank you.
             Siyuan

**Comment by elhoangvu** [comment]
Hi @lsy17096535 ,
I am very happy that you are the HyperLandmark's author interested in my iOS project I ported.
Thank you very much for your open source, it's great.
You can contact me by email: elhoangvu@gmail.com.

Best regards,
elhoangvu
